version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: bloodbank-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - bloodbank-network

  backend:
    build: .
    container_name: bloodbank-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - MONGO_URL=mongodb://admin:password123@mongodb:27017/bloodbank?authSource=admin
      - JWT_SECRET=your-super-secret-jwt-key-here
      - CLIENT_URL=http://localhost:8080
    depends_on:
      - mongodb
    networks:
      - bloodbank-network
    volumes:
      - ./logs:/app/logs

volumes:
  mongodb_data:

networks:
  bloodbank-network:
    driver: bridge
